name: mirror docker hub image

on: workflow_dispatch

env:
  IMAGES: |
    ruby:2.7-slim
    ruby:2.7.4-slim
  REPOSITORY: ghcr.io/hogelog/ecr-mirror
jobs:
  mirror:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          for image in $IMAGES; do
            ghcr_image=$REPOSITORY/$image
            docker pull $image && docker tag $image $ghcr_image && docker push $ghcr_image || true
          done
